app_name = "skeleton"
main_core = 0
worker_cores = []
dpdk_args = "-v --log-level eal:8"

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "cap0"
    device = "net_ring0"
    rx_cores = [0]
    tx_cores = [0]
