app_name = "nat64"
master_core = 0

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "eth1"
    device = "0000:00:08.0"
    cores = [1]

[[ports]]
    name = "eth2"
    device = "0000:00:09.0"
    cores = [1]
