mod mbuf;
mod mempool;
mod port;

pub use mbuf::*;
pub use mempool::*;
pub use port::*;

use crate::ffi;
use crate::ffi::{AsStr, ToRaw, ToResult};
use failure::{Error, Fail};
use std::os::raw;

/// An error generated by libdpdk.
#[derive(Debug, Fail)]
#[fail(display = "{}", _0)]
pub struct DpdkError(String);

impl DpdkError {
    #[inline]
    pub(crate) fn new() -> Self {
        let msg = unsafe { ffi::rte_strerror(ffi::_rte_errno()) };
        DpdkError(msg.as_str().into())
    }
}

/// Initialize the Environment Abstraction Layer (EAL).
pub fn eal_init(args: Vec<String>) -> Result<(), Error> {
    unsafe {
        let len = args.len() as raw::c_int;
        let args = args
            .into_iter()
            .map(|s| s.to_raw())
            .collect::<Vec<_>>()
            .as_mut_ptr();

        ffi::rte_eal_init(len, args).to_result().map(|_| ())
    }
}
