mod mbuf;
mod mempool;
mod port;

pub use mbuf::*;
pub use mempool::*;
pub use port::*;

use crate::ffi::{self, AsStr, ToCString, ToResult};
use failure::{Error, Fail};
use log::debug;
use std::os::raw;

/// An error generated by libdpdk.
#[derive(Debug, Fail)]
#[fail(display = "{}", _0)]
pub struct DpdkError(String);

impl DpdkError {
    #[inline]
    pub(crate) fn new() -> Self {
        let errno = unsafe { ffi::_rte_errno() };
        DpdkError::new_with_errno(errno)
    }

    #[inline]
    pub(crate) fn new_with_errno(errno: raw::c_int) -> Self {
        let msg = unsafe { ffi::rte_strerror(errno) };
        DpdkError(msg.as_str().into())
    }
}

/// An opaque identifier for a physical CPU socket.
#[derive(Copy, Clone, Debug, Eq, Hash, PartialEq)]
pub struct SocketId(raw::c_uint);

impl SocketId {
    /// Returns the ID of the socket the current core is on.
    pub fn current() -> SocketId {
        unsafe { SocketId(ffi::rte_socket_id()) }
    }
}

/// An opaque identifier for a physical CPU core.
#[derive(Copy, Clone, Debug, Eq, Hash, PartialEq)]
pub struct CoreId(raw::c_uint);

impl CoreId {
    /// Returns the ID of the current core.
    pub fn current() -> CoreId {
        unsafe { CoreId(ffi::_rte_lcore_id()) }
    }

    /// Returns the ID of the socket the core is on.
    pub fn socket_id(&self) -> SocketId {
        unsafe { SocketId(ffi::_rte_lcore_to_socket_id(self.0)) }
    }
}

/// Initialize the Environment Abstraction Layer (EAL).
pub fn eal_init(args: Vec<String>) -> Result<(), Error> {
    let len = args.len() as raw::c_int;
    let mut args = args
        .into_iter()
        .map(|s| s.to_cstring().into_raw())
        .collect::<Vec<_>>();

    let res = unsafe { ffi::rte_eal_init(len, args.as_mut_ptr()) };
    debug!("EAL parsed {} arguments.", res);

    // EAL does not take ownership of the raw pointers. we should reclaim them
    // to free properly. but if we do, they are actually double-freed somehow
    // and cause heap corruption. don't quite understand this.

    // args.into_iter().for_each(|p| unsafe {
    //     let _ = CString::from_raw(p);
    // });

    res.to_result().map(|_| ())
}
