[package]
name = "skeleton"
version = "0.1.0"
authors = ["William of Ockham <occam_engineering@comcast.com>"]
license = "TBD"
keywords = ["dpdk", "nfv"]
edition = "2018"

[[bin]]
name = "skeleton"
path = "main.rs"
doctest = false

[dependencies]
failure = "0.1"
nb2 = { path = "../../core" }
tracing = "0.1"
tracing-subscriber = "0.1"
