app_name = "ping4d"
master_core = 0
duration = 5

[mempool]
    capacity = 65535
    cache_size = 256

[[ports]]
    name = "eth1"
    device = "net_pcap0"
    args = "rx_pcap=echo.pcap,tx_iface=lo"
    cores = [0]
