[package]
name = "nb2-ffi"
version = "18.11.2"
authors = ["William of Ockham <occam_engineering@comcast.com>"]
license = "TBD"
keywords = ["dpdk", "nfv"]
edition = "2018"

[lib]
name = "nb2_ffi"
path = "lib.rs"
doctest = false

[build-dependencies]
bindgen = "0.51"
cc = "1.0"

[dependencies]
